### ISSUE TITLE
Django 4.1 Deprecation Warning

### ISSUE THREAD

**Issue by nbhargava** [matthiask/django-admin-sso#11]
`default_app_config` is set in `django-admin-sso/admin_sso/__init__.py`, but is marked for deprecation:
```
RemovedInDjango41Warning: 'admin_sso' defines default_app_config = 'admin_sso.apps.AdminSSOConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

Might be worth conditionally setting it, like is done [here](https://github.com/django-waffle/django-waffle/blob/master/waffle/__init__.py#L10), to suppress the warning!

**Comment by matthiask** [comment]
I started dropping support for Python < 3.8 and Django < 3.2 in all of my packages. This means it isn't even necessary to set the value conditionally, it can just be removed altogether. 

Do you want to submit a pull request?

**Comment by matthiask** [comment]
django-admin-sso==5.0 should fix this issue.
