### ISSUE TITLE
Is there a way to create a generic rule/convention for mapping OAuth providers username with the username in django?

### ISSUE THREAD

**Issue by vaidik** [matthiask/django-admin-sso#4]
I have to create one assignment of every user I want to give access to the admin. I might have several such users. And doing this every time is not feasible.

Ideally what I would want is:
1. Every user gets a default assignemnt. For example, vaidik@google.com gets matched to "vaidik" Django user.
2. If the user does not exist, a user is created in Django and a default group is assigned to it.

Is there a way to achieve something like this using this package?

**Comment by matthiask** [comment]
I don't think there's a straightforward way to achieve this using django-admin-sso. But maybe there is a way to do this with django-authlib's `GoogleOAuth2Client`, see e.g. https://django-authlib.readthedocs.io/en/latest/ or https://github.com/matthiask/django-authlib/blob/64202f626b00eddcb62c7b228882bac0448e81c2/authlib/admin_oauth/views.py#L17-L33 for possible inspiration.

**Comment by vaidik** [comment]
Super helpful. Thanks
