### ISSUE TITLE
Does this library respect the "next" parameter?

### ISSUE THREAD

**Issue by asgoel** [matthiask/django-admin-sso#9]
If I open up a page in the admin and am not logged in, I get redirected to the login page, with the `next` url parameter set to the original page I was trying to reach. However, after completing SSO I am just redirected to the admin index page instead of the "next" url that I was originally trying to reach. Is this intended?

**Comment by matthiask** [comment]
It unfortunately doesn't. Nobody got around to implementing this. (A bigger problem is that django-admin-sso still uses the deprecated `auth2client` library https://pypi.org/project/oauth2client/)

django-authlib's admin_oauth module supports it https://django-authlib.readthedocs.io/en/latest/#admin-oauth2 but it's Google-only at the moment.
